name: Compress PixelUI

on:
  push:
    branches:
      - main

jobs:
  compress:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
          
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
        
      - name: Install LuaSrcDiet
        run: luarocks install luasrcdiet
        
      - name: Create compressed directory
        run: mkdir -p compressed
        
      - name: Compress pixelui.lua
        run: |
          luasrcdiet pixelui.lua -o compressed/pixelui.lua --opt-comments --opt-whitespace --opt-emptylines --opt-numbers --opt-locals
          
      - name: Commit compressed file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add compressed/pixelui.lua
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-compress pixelui.lua"
            git push
          fi
